/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_lsh_Main */

#ifndef _Included_org_lsh_Main
#define _Included_org_lsh_Main
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_lsh_Main
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_org_lsh_Main_sum
        (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
